
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./app/backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped